symfonycasts_tailwind:
    input_css: 'assets/styles/index.css'
    # Specify the EXACT version of Tailwind CSS you want to use
    binary_version: 'v4.0.14'

# when@dev:
    # symfonycasts_tailwind:
        # binary: 'node_modules/.bin/tailwindcss'
